# Generated by Django 3.2 on 2023-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fayapp', '0002_payment_id_investment_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='investment_plan_name',
            field=models.CharField(blank=True, default='MISSED-INFO', max_length=20, null=True),
        ),
    ]
