# Generated by Django 3.2 on 2023-09-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fayapp', '0003_client_investment_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract_duration',
            field=models.FloatField(blank=True, default=180, null=True),
        ),
        migrations.AddField(
            model_name='payment_id',
            name='contract_duration',
            field=models.FloatField(blank=True, default=180, null=True),
        ),
    ]
